### ISSUE TITLE
The auto repin on cluster

### ISSUE THREAD

**Issue by ddok2** [ipfs-cluster/ipfs-cluster#1734]
**Additional information:**
 - OS: MacOS 
 - IPFS Cluster version: `ipfs/ipfs-cluster:latest `on Dockerhub
 - Installation method: Docker(peers run inside docker-compose stack)

**Describe the bug:**

**short:**
1. Run 5 cluster peers on docker-compose stack. 
2. Add file, replication factor 2-4, cid=`QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw`
3. Stop a cluster peer, peerID=`12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV`
4. See the `repinned` log on one of cluster peer
5. Run `pin ls` like this:
```
docker exec -it cluster1 ipfs-cluster-ctl pin ls QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw |  | PIN | Repl. Factor: 2--4 | Allocations: [12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C 12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN 12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV] | Recursive | Metadata: no | Exp: ∞ | Added: 2022-08-04 03:20:36
```
6. I found dead cluster peerID at `Allocations`
7. **I expected that the pin don't have dead peer ID on allocations after repin. but it's not.**
8. Am I thinking wrong?

**long:**
1. Run docker-compose stack, docker-compose look like this:
```
version: '3.4'

volumes:
  ipfs0:
  ipfs1:
  ipfs2:
  ipfs3:
  ipfs4:
  cluster0:
  cluster1:
  cluster2:
  cluster3:
  cluster4:

services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs0:/data/ipfs
  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: 52dad9c4f110735cfa5a2d9617a0851ce5b64257a935b337854798e672b3de39
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discover
      CLUSTER_DISABLEREPINNING: false
    ports:
      - "9094:9094"
      - "9096:9096"
    volumes:
      - cluster0:/data/ipfs-cluster

  ipfs1:
    container_name: ipfs1
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs1:/data/ipfs
  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: 52dad9c4f110735cfa5a2d9617a0851ce5b64257a935b337854798e672b3de39
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_DISABLEREPINNING: false
    volumes:
      - cluster1:/data/ipfs-cluster

  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs2:/data/ipfs

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: 52dad9c4f110735cfa5a2d9617a0851ce5b64257a935b337854798e672b3de39
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_DISABLEREPINNING: false
    volumes:
      - cluster2:/data/ipfs-cluster

  ipfs3:
    container_name: ipfs3
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs3:/data/ipfs

  cluster3:
    container_name: cluster3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs3
    environment:
      CLUSTER_PEERNAME: cluster3
      CLUSTER_SECRET: 52dad9c4f110735cfa5a2d9617a0851ce5b64257a935b337854798e672b3de39
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs3/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_DISABLEREPINNING: false
    volumes:
      - cluster3:/data/ipfs-cluster

  ipfs4:
    container_name: ipfs4
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs4:/data/ipfs

  cluster4:
    container_name: cluster4
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs4
    environment:
      CLUSTER_PEERNAME: cluster4
      CLUSTER_SECRET: 52dad9c4f110735cfa5a2d9617a0851ce5b64257a935b337854798e672b3de39
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs4/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_DISABLEREPINNING: false
    volumes:
      - cluster4:/data/ipfs-cluster
```
2. All peers look like this:
```
$ ipfs-cluster-ctl peers ls

12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN | cluster0 | Sees 4 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN
    - /ip4/172.18.0.11/tcp/9096/p2p/12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN
  > IPFS: 12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/168.119.212.120/tcp/4001/p2p/12D3KooWFUbNVkMuN7eGZrsa5MuLezwsxPRFsPvqvYTtHUFJ3KnY/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/168.119.212.120/udp/4001/quic/p2p/12D3KooWFUbNVkMuN7eGZrsa5MuLezwsxPRFsPvqvYTtHUFJ3KnY/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/172.18.0.6/tcp/4001/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/172.18.0.6/udp/4001/quic/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/198.211.106.107/tcp/4001/p2p/12D3KooWBn25nXsivuCA9PVN7AwpXNddunRbRx1NEPmzg9dBKdPK/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip4/198.211.106.107/udp/43554/quic/p2p/12D3KooWBn25nXsivuCA9PVN7AwpXNddunRbRx1NEPmzg9dBKdPK/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip6/2a01:4f8:251:1c47::2/tcp/4001/p2p/12D3KooWFUbNVkMuN7eGZrsa5MuLezwsxPRFsPvqvYTtHUFJ3KnY/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip6/2a01:4f8:251:1c47::2/udp/4001/quic/p2p/12D3KooWFUbNVkMuN7eGZrsa5MuLezwsxPRFsPvqvYTtHUFJ3KnY/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip6/64:ff9b::c6d3:6a6b/tcp/4001/p2p/12D3KooWBn25nXsivuCA9PVN7AwpXNddunRbRx1NEPmzg9dBKdPK/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
    - /ip6/64:ff9b::c6d3:6a6b/udp/43554/quic/p2p/12D3KooWBn25nXsivuCA9PVN7AwpXNddunRbRx1NEPmzg9dBKdPK/p2p-circuit/p2p/12D3KooWRE1DpF75EFPC6zzXq8ESv1w7HsEo7CJBxDSZtoRfeMzR
12D3KooWAHvW255vVY1yTmFYRU8EkjyggcyNARZZtMstUuktRnWg | cluster3 | Sees 4 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWAHvW255vVY1yTmFYRU8EkjyggcyNARZZtMstUuktRnWg
    - /ip4/172.18.0.9/tcp/9096/p2p/12D3KooWAHvW255vVY1yTmFYRU8EkjyggcyNARZZtMstUuktRnWg
  > IPFS: 12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/164.90.188.231/tcp/4001/p2p/QmbKfH7uTaoZoPcMcMrbWzS5FuiVraJKjhK5vgbnKRbdRM/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/168.119.172.178/tcp/4001/p2p/12D3KooWDXvBTyoFtdh3WZt18oQs9rEgBVVgoo2YPW9WFsgvbF1Z/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/168.119.172.178/udp/4001/quic/p2p/12D3KooWDXvBTyoFtdh3WZt18oQs9rEgBVVgoo2YPW9WFsgvbF1Z/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/172.18.0.4/tcp/4001/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip4/172.18.0.4/udp/4001/quic/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip6/2a01:4f8:c0c:9d86::1/tcp/4001/p2p/12D3KooWDXvBTyoFtdh3WZt18oQs9rEgBVVgoo2YPW9WFsgvbF1Z/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip6/2a01:4f8:c0c:9d86::1/udp/4001/quic/p2p/12D3KooWDXvBTyoFtdh3WZt18oQs9rEgBVVgoo2YPW9WFsgvbF1Z/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip6/2a03:b0c0:3:d0::1970:d001/tcp/4001/p2p/QmbKfH7uTaoZoPcMcMrbWzS5FuiVraJKjhK5vgbnKRbdRM/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip6/64:ff9b::a45a:bce7/tcp/4001/p2p/QmbKfH7uTaoZoPcMcMrbWzS5FuiVraJKjhK5vgbnKRbdRM/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
    - /ip6/64:ff9b::a877:acb2/udp/4001/quic/p2p/12D3KooWDXvBTyoFtdh3WZt18oQs9rEgBVVgoo2YPW9WFsgvbF1Z/p2p-circuit/p2p/12D3KooWKYinDzF2BNHhTvZxH4RpeLDBzc3JcsxpkkvMjpcS4jqv
12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C | cluster2 | Sees 4 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C
    - /ip4/172.18.0.8/tcp/9096/p2p/12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C
  > IPFS: 12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/155.4.231.137/tcp/22096/p2p/12D3KooWHn9cqrJs6KyWWzz9kMVw7S1cXSyQtpbsoUnaGijycyrK/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/155.4.231.137/udp/22096/quic/p2p/12D3KooWHn9cqrJs6KyWWzz9kMVw7S1cXSyQtpbsoUnaGijycyrK/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/159.89.188.147/tcp/4001/p2p/12D3KooWBt8Y6oHkXqu2dGGDeyFqj35vr8rcQ4J4SR393gNPsfcH/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/159.89.188.147/udp/4001/quic/p2p/12D3KooWBt8Y6oHkXqu2dGGDeyFqj35vr8rcQ4J4SR393gNPsfcH/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/172.18.0.3/tcp/4001/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip4/172.18.0.3/udp/4001/quic/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip6/64:ff9b::9f59:bc93/tcp/4001/p2p/12D3KooWBt8Y6oHkXqu2dGGDeyFqj35vr8rcQ4J4SR393gNPsfcH/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
    - /ip6/64:ff9b::9f59:bc93/udp/4001/quic/p2p/12D3KooWBt8Y6oHkXqu2dGGDeyFqj35vr8rcQ4J4SR393gNPsfcH/p2p-circuit/p2p/12D3KooWBCQmvtPVLBoUFirEF3jJuPSNkajpVGWAUKFq7zFQPDcd
12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN | cluster1 | Sees 4 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN
    - /ip4/172.18.0.7/tcp/9096/p2p/12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN
  > IPFS: 12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/142.93.108.62/tcp/4001/p2p/QmUGCr3msQ5pVFKcxRvK53AChUyUYQHKDqjDKPKcS2YBNK/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/172.18.0.2/tcp/4001/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/172.18.0.2/udp/4001/quic/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/99.81.187.79/tcp/4001/p2p/QmTi6uTbq7mkPcHnroGeuvgL5x8Ng4vFk3R6EaLPzDLLos/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip4/99.81.187.79/udp/4001/quic/p2p/QmTi6uTbq7mkPcHnroGeuvgL5x8Ng4vFk3R6EaLPzDLLos/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip6/2a03:b0c0:3:d0::130c:e001/tcp/4001/p2p/QmUGCr3msQ5pVFKcxRvK53AChUyUYQHKDqjDKPKcS2YBNK/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip6/64:ff9b::6351:bb4f/udp/4001/quic/p2p/QmTi6uTbq7mkPcHnroGeuvgL5x8Ng4vFk3R6EaLPzDLLos/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
    - /ip6/64:ff9b::8e5d:6c3e/tcp/4001/p2p/QmUGCr3msQ5pVFKcxRvK53AChUyUYQHKDqjDKPKcS2YBNK/p2p-circuit/p2p/12D3KooWCKHP5oPsP8mpf1WMjXb5nhYcWHcMAy7v4BCJ793fzjQT
12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV | cluster4 | Sees 4 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV
    - /ip4/172.18.0.10/tcp/9096/p2p/12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV
  > IPFS: 12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/154.31.2.17/tcp/4001/p2p/12D3KooWKqHoXmj694eoNoKXCAwNPvQoZAGMcyms7cbTu9qTU8RB/p2p-circuit/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/154.31.2.17/udp/4001/quic/p2p/12D3KooWKqHoXmj694eoNoKXCAwNPvQoZAGMcyms7cbTu9qTU8RB/p2p-circuit/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/172.18.0.5/tcp/4001/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/172.18.0.5/udp/4001/quic/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/47.114.114.111/tcp/4001/p2p/12D3KooWCp2EoAJk33pL8tiVxLER1LDDMZFCXRweMZKe1bvKuRuo/p2p-circuit/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip4/47.114.114.111/udp/4001/quic/p2p/12D3KooWCp2EoAJk33pL8tiVxLER1LDDMZFCXRweMZKe1bvKuRuo/p2p-circuit/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz
    - /ip6/64:ff9b::9a1f:211/udp/4001/quic/p2p/12D3KooWKqHoXmj694eoNoKXCAwNPvQoZAGMcyms7cbTu9qTU8RB/p2p-circuit/p2p/12D3KooWDfYvMwu5yjXdg2STG4DL7mKPBGA919tJogRoqWrW6Mqz

```

3. Add file like this:
```
$ ipfs-cluster-ctl add testfile --rmin 2 --rmax 4
added QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw testfile


$ ipfs-cluster-ctl status QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw:
    > cluster3             : REMOTE | 2022-08-04T03:19:14.360264809Z | Attempts: 0 | Priority: false
    > cluster2             : PINNED | 2022-08-04T03:18:54Z | Attempts: 0 | Priority: false
    > cluster1             : PINNED | 2022-08-04T03:18:54Z | Attempts: 0 | Priority: false
    > cluster0             : PINNED | 2022-08-04T03:18:54Z | Attempts: 0 | Priority: false
    > cluster4             : PINNED | 2022-08-04T03:18:54Z | Attempts: 0 | Priority: false

$ ipfs-cluster-ctl pin ls QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw |  | PIN | Repl. Factor: 2--4 | Allocations: [12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C 12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN 12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV] | Recursive | Metadata: no | Exp: ∞ | Added: 2022-08-04 03:18:54
```
4. Stop a cluster like this:
```
# cluster4 peer.id = 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV
$ docker stop cluster4
```
5. One of cluster peer show this log:
```
# cluster1 log
2022-08-04T03:20:36.204Z	WARN	cluster	ipfs-cluster/cluster.go:492	metric alert for ping: Peer: 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV.
2022-08-04T03:20:36.205Z	INFO	cluster	ipfs-cluster/cluster.go:1598	pinning QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw on [12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV 12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN 12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN]:
2022-08-04T03:20:36.207Z	INFO	crdt	crdt/consensus.go:243	new pin added: QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
2022-08-04T03:20:36.211Z	INFO	cluster	ipfs-cluster/cluster.go:646	repinned QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw out of 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV
2022-08-04T03:21:06.184Z	WARN	cluster	ipfs-cluster/cluster.go:492	metric alert for freespace: Peer: 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV.
2022-08-04T03:21:06.184Z	WARN	cluster	ipfs-cluster/cluster.go:492	metric alert for tag:group: Peer: 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV.
2022-08-04T03:21:06.184Z	WARN	cluster	ipfs-cluster/cluster.go:492	metric alert for pinqueue: Peer: 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV.
```
6.  See `pin ls` like this:
```
$ docker exec -it cluster1 ipfs-cluster-ctl pin ls QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw |  | PIN | Repl. Factor: 2--4 | Allocations: [12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C 12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN 12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN 12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV] | Recursive | Metadata: no | Exp: ∞ | Added: 2022-08-04 03:20:36
```
7. Found cluster4 peerID on `Allocations`
```
# cid = QmexHYhAASozJkYCcFJWsjjc8uBS2z9CuvrGf4jjNtjNNw
Allocations: [
  12D3KooWE3ZB1LU3DhTGCZJMisTQNQYHj9MVJDTFMsP5Pkifj67C
  12D3KooWGrjqQqK9KFGSmm7MugBdp5WY1rMbV5vmNBYrBxm44MmN
  12D3KooWJ1xR2U2zUhXhWJXWE21jFZLNPADC5om2GHSo5feYbHqN
  12D3KooWKvQ5h2qpF2H3aoDGYxyAUYZmsLQhHKuPyvxnbBcyDvMV // cluster4 peerID
] 

```
